services:
  - type: web
    name: meditrack-backend
    runtime: node
    buildCommand: bun install --frozen-lockfile
    startCommand: bun run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: BETTER_AUTH_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: CLIENT_DOMAIN
        sync: false
      - key: DB_URL
        sync: false
